### ISSUE TITLE
Category.hs doesn't compile for me

### ISSUE THREAD

**Issue by jrp2014** [ekmett/nominal#1]
Looking forward to watching the next, epic, episode (ideally on Utube; the Amazon ads are intrusive).

I'm trying to cabal new-build this repo with 8.6.1, but I get:

`src/Nominal/Category.hs:65:35: error:
    • Expected kind ‘* -> * -> *’, but ‘a’ has kind ‘*’
    • In the first argument of ‘k’, namely ‘(a * c)’
      In the type signature: (***) :: k a b -> k c d -> k (a * c) (b * d)
      In the class declaration for ‘MonoidalP’
   |
65 |   (***)   :: k a b -> k c d -> k (a*c) (b*d)
   |                                   ^^^

src/Nominal/Category.hs:65:41: error:
    • Expected kind ‘* -> * -> *’, but ‘b’ has kind ‘*’
    • In the second argument of ‘k’, namely ‘(b * d)’
      In the type signature: (***) :: k a b -> k c d -> k (a * c) (b * d)
      In the class declaration for ‘MonoidalP’
   |
65 |   (***)   :: k a b -> k c d -> k (a*c) (b*d)
   |                                         ^^^

src/Nominal/Category.hs:66:26: error:
    • Expected kind ‘* -> k0 -> *’, but ‘a’ has kind ‘*’
    • In the first argument of ‘k’, namely ‘(a * c)’
      In the type signature: first :: k a b -> k (a * c) (b * c)
      In the class declaration for ‘MonoidalP’
   |
66 |   first   :: k a b -> k (a*c) (b*c)
   |                          ^^^

src/Nominal/Category.hs:66:32: error:
    • Expected kind ‘* -> k0 -> *’, but ‘b’ has kind ‘*’
    • In the second argument of ‘k’, namely ‘(b * c)’
      In the type signature: first :: k a b -> k (a * c) (b * c)
      In the class declaration for ‘MonoidalP’
   |
66 |   first   :: k a b -> k (a*c) (b*c)

:
`

**Comment by jrp2014** [comment]
.. as a further compatibility issue, using the Haskell for Mac 1.6.0 (which uses stockage-lts-9.6), the cabal files don't grok with `nominal.cabal:66: 'library'expects no argument` and `nominal.cabal:5: Parse of field 'license' failed.`. The latter is sorted by setting a single license type.  The former is less straightforward because there can only be one library description in a package description, apparently.  (This with the bundled cabal 1.24.0.2.).  Shame that the guy that produce Haskell for Mac has not updated to a more recent GHC/Cabal, but he seems to be fairly busy professionalising the GHC release process, so cannot be everywhere at once.

**Comment by ekmett** [comment]
I'm afraid I'm currently locking things to cabal 2.2, and ghc 8.4.3 which means you'll need to use cabal to build rather than stack for now. I plan to use backpack for some things soon and so reverting now just to flip right back probably isn't that helpful.

**Comment by ekmett** [comment]
LTS-9.6 is locked back on GHC 8.0, which means losing semigroup as a superclass of monoid, backpack, and a whole bunch of other stuff.

**Comment by ekmett** [comment]
`stack` is still missing support for the backpack and multiple libraries at this time. `cabal` added support in 2.0, and fleshed that support out in 2.2.

**Comment by ekmett** [comment]
I should bump the floor on the base version to at least get a hard failure on compiling.

**Comment by jrp2014** [comment]
Thanks.

**Comment by jrp2014** [comment]
A bit of further playing suggests that, with 8.6.1, the `type (*) = (,)`at line 38 of `Category.hs` doesn't get interpreted correctly.   This is because of https://ghc.haskell.org/trac/ghc/wiki/Migration/8.6 which points out that GHC treats * as a synonym for Type (from Data.Kind) instead of a binary type operator.  There are various possible fixes.

**Comment by ekmett** [comment]
I guess I'll pick another symbol then. =)

**Comment by ekmett** [comment]
Switched to `(,)`. That should address the primary issue raised here.

The Haskell for Mac issue is unfortunate, but will probably have to remain unresolved.
